### ISSUE TITLE
Using schema to support smart contract JSON parameters

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-net-sdk#68]
**Task description**

Add functionality for using the smart contract schema to convert bytes to and from JSON. 
This is relevant for smart contract parameters, events and return types.

**Sub-tasks**
- [x] Extract schema bytes from a smart contract module source ([embedding](https://developer.concordium.software/en/mainnet/smart-contracts/general/contract-schema.html#embedding-schemas-on-chain)).
- [x] Functionality for turning bytes and the schema into JSON.
- [ ] Functionality for turning JSON and the schema into bytes.

**Comment by limemloh** [comment]
For the last two items, we will need to decide whether to implement and maintain all of this functionality directly in C# or whether to reuse the Rust implementation through FFI.
The FFI will be needed anyway at a later point for encrypted transfers.

**Comment by abizjak** [comment]
As we discussed at the daily today, unless there are blocking issues we should not implement this in C#.

There is just too much complexity to implement and maintain.

**Comment by limemloh** [comment]
Remaining tasks are tracked in #94
